### ISSUE TITLE
contact info

### ISSUE THREAD

**Issue by gittssz1** [WAZAAAAA0/FagNet#2]
I saw you everywhere , and I have simple questions to ask you ; I will not ask you how to install fagnet or anything

I'm writing here because I can't find the contact address, I hope you see

**Comment by WAZAAAAA0** [comment]
I don't get it
My contact? What's the point, I didn't make this 
wtfblub's contact? This project is old, archived, and moved elsewhere, but I guess you can try through GitLab

**Comment by gittssz1** [comment]
hey, I know everything 
can u come here https://discord.gg/RWg2xWRd I have a special question for you
